import type { AnalysisField } from './claude.js';
import type { DataLine } from './types.js';

export type LiveValuePrimitive = string | number | boolean;

export interface LiveValue {
  value: LiveValuePrimitive;
  rawMatch: string;
  timestamp: number;
}

export interface ParsedStream {
  /** fieldName → history of parsed values (newest last) */
  history: Record<string, LiveValue[]>;
  /** fieldName → compiled regex or null if missing/invalid */
  compiledRegex: Record<string, RegExp | null>;
  /** how many fields have usable regex */
  parsableFieldCount: number;
}

const MAX_HISTORY = 60;
const MAX_PATTERN_LEN = 300;

/** Reject obviously ReDoS-prone patterns generated by the model — nested
 *  quantifiers like (a+)+ or (a*)*b cause exponential backtracking and can
 *  freeze the UI thread. Not exhaustive, but catches the common footguns. */
function isSuspiciousPattern(pattern: string): boolean {
  if (pattern.length > MAX_PATTERN_LEN) return true;
  // Grouped quantifier followed by outer quantifier: (x+)+ (x*)* (x+)* etc.
  if (/\([^)]*[+*][^)]*\)\s*[+*]/.test(pattern)) return true;
  // Repeated overlapping alternation with quantifier: (a|a)+
  if (/\(([^|)]+)\|\1\)[+*]/.test(pattern)) return true;
  return false;
}

function compile(pattern: string | undefined): RegExp | null {
  if (!pattern) return null;
  if (isSuspiciousPattern(pattern)) return null;
  try {
    return new RegExp(pattern);
  } catch {
    return null;
  }
}

export function compileFields(fields: AnalysisField[]): Record<string, RegExp | null> {
  const result: Record<string, RegExp | null> = {};
  for (const f of fields) result[f.name] = compile(f.regex);
  return result;
}

function parseHex(raw: string): number | null {
  const cleaned = raw.replace(/[\s_]/g, '').toLowerCase();
  if (!/^[0-9a-f]+$/.test(cleaned)) return null;
  const n = parseInt(cleaned, 16);
  return isNaN(n) ? null : n;
}

function coerce(raw: string, dataType?: AnalysisField['data_type']): LiveValuePrimitive {
  if (dataType === 'number') {
    const n = parseFloat(raw);
    return isNaN(n) ? raw : n;
  }
  if (dataType === 'boolean') {
    const lower = raw.toLowerCase().trim();
    return lower === 'true' || lower === '1' || lower === 'yes' || lower === 'on';
  }
  if (dataType === 'hex_u16_be') {
    // Big-endian 16-bit unsigned. Capture should be exactly 2 bytes.
    const n = parseHex(raw);
    return n === null ? raw : n & 0xffff;
  }
  if (dataType === 'hex_u16_le') {
    // Little-endian: reverse byte order before interpreting.
    const cleaned = raw.replace(/[\s_]/g, '');
    if (cleaned.length !== 4) return raw;
    const lo = parseInt(cleaned.slice(0, 2), 16);
    const hi = parseInt(cleaned.slice(2, 4), 16);
    if (isNaN(lo) || isNaN(hi)) return raw;
    return ((hi << 8) | lo) & 0xffff;
  }
  if (dataType === 'hex_s16_be') {
    // Signed 16-bit big-endian (two's complement).
    const n = parseHex(raw);
    if (n === null) return raw;
    const u = n & 0xffff;
    return u > 0x7fff ? u - 0x10000 : u;
  }
  if (dataType === 'hex_u8') {
    const n = parseHex(raw);
    return n === null ? raw : n & 0xff;
  }
  return raw;
}

export function parseStream(lines: DataLine[], fields: AnalysisField[]): ParsedStream {
  const compiledRegex = compileFields(fields);
  const history: Record<string, LiveValue[]> = {};
  let parsableFieldCount = 0;

  for (const f of fields) {
    history[f.name] = [];
    if (compiledRegex[f.name]) parsableFieldCount++;
  }

  for (const line of lines) {
    for (const field of fields) {
      const re = compiledRegex[field.name];
      if (!re) continue;
      // Binary protocols (match_hex) run the regex against the hex
      // representation so byte offsets can be captured directly.
      const target = field.match_hex ? line.hex : line.ascii;
      const match = target.match(re);
      if (!match) continue;
      const groupIdx = field.capture_group ?? 1;
      const raw = match[groupIdx] ?? match[0];
      history[field.name].push({
        value: coerce(raw, field.data_type),
        rawMatch: match[0],
        timestamp: line.timestamp,
      });
      if (history[field.name].length > MAX_HISTORY) {
        history[field.name].shift();
      }
    }
  }

  return { history, compiledRegex, parsableFieldCount };
}

export function latest(history: LiveValue[]): LiveValue | null {
  return history.length > 0 ? history[history.length - 1] : null;
}

export function numericHistory(history: LiveValue[]): number[] {
  const nums: number[] = [];
  for (const entry of history) {
    if (typeof entry.value === 'number') nums.push(entry.value);
  }
  return nums;
}
